/**
 * Dota 2 Item Constants
 * 
 * Maps item IDs to internal names used in CDN URLs.
 * Source: https://api.opendota.com/api/constants/items
 */

export const ITEM_NAMES: Record<number, string> = {
    // Basic Items
    1: "blink",
    2: "blades_of_attack",
    3: "broadsword",
    4: "chainmail",
    5: "claymore",
    6: "helm_of_iron_will",
    7: "javelin",
    8: "mithril_hammer",
    9: "platemail",
    10: "quarterstaff",
    11: "quelling_blade",
    12: "ring_of_protection",
    13: "gauntlets",
    14: "slippers",
    15: "mantle",
    16: "branches",
    17: "belt_of_strength",
    18: "boots_of_elves",
    19: "robe",
    20: "circlet",
    21: "ogre_axe",
    22: "blade_of_alacrity",
    23: "staff_of_wizardry",
    24: "ultimate_orb",
    25: "gloves",
    26: "lifesteal",
    27: "ring_of_regen",
    28: "sobi_mask",
    29: "boots",
    30: "gem",
    31: "cloak",
    32: "talisman_of_evasion",
    33: "cheese",
    34: "magic_stick",
    36: "magic_wand",
    37: "ghost",
    38: "clarity",
    39: "flask",
    40: "dust",
    41: "bottle",
    42: "ward_observer",
    43: "ward_sentry",
    44: "tango",
    46: "tpscroll",
    48: "travel_boots",
    50: "phase_boots",
    51: "demon_edge",
    52: "eagle",
    53: "reaver",
    54: "relic",
    55: "hyperstone",
    56: "ring_of_health",
    57: "void_stone",
    58: "mystic_staff",
    59: "energy_booster",
    60: "point_booster",
    61: "vitality_booster",
    63: "power_treads",
    65: "hand_of_midas",
    67: "oblivion_staff",
    69: "pers",
    73: "bracer",
    75: "wraith_band",
    77: "null_talisman",
    79: "mekansm",
    81: "vladmir",
    86: "buckler",
    88: "ring_of_basilius",
    90: "pipe",
    92: "urn_of_shadows",
    94: "headdress",
    96: "sheepstick",
    98: "orchid",
    100: "cyclone",
    102: "force_staff",
    104: "dagon",
    108: "ultimate_scepter",
    110: "refresher",
    112: "assault",
    114: "heart",
    116: "black_king_bar",
    117: "aegis",
    119: "shivas_guard",
    121: "bloodstone",
    123: "sphere",
    125: "vanguard",
    127: "blade_mail",
    129: "soul_booster",
    131: "hood_of_defiance",
    133: "rapier",
    135: "monkey_king_bar",
    137: "radiance",
    139: "butterfly",
    141: "greater_crit",
    143: "basher",
    145: "bfury",
    147: "manta",
    149: "lesser_crit",
    151: "armlet",
    152: "invis_sword",
    154: "sange_and_yasha",
    156: "satanic",
    158: "mjollnir",
    160: "skadi",
    162: "sange",
    164: "helm_of_the_dominator",
    166: "maelstrom",
    168: "desolator",
    170: "yasha",
    172: "mask_of_madness",
    174: "diffusal_blade",
    176: "ethereal_blade",
    178: "soul_ring",
    180: "arcane_boots",
    181: "orb_of_venom",
    185: "ancient_janggo",
    187: "medallion_of_courage",
    188: "smoke_of_deceit",
    190: "veil_of_discord",
    196: "diffusal_blade_2",
    201: "dagon_2",
    202: "dagon_3",
    203: "dagon_4",
    204: "dagon_5",
    206: "rod_of_atos",
    208: "abyssal_blade",
    210: "heavens_halberd",
    214: "tranquil_boots",
    215: "shadow_amulet",
    216: "enchanted_mango",
    218: "ward_dispenser",
    220: "travel_boots_2",
    223: "meteor_hammer",
    225: "nullifier",
    226: "lotus_orb",
    229: "solar_crest",
    231: "guardian_greaves",
    232: "aether_lens",
    235: "octarine_core",
    236: "dragon_lance",
    237: "faerie_fire",
    240: "blight_stone",
    242: "crimson_guard",
    244: "wind_lace",
    247: "moon_shard",
    249: "silver_edge",
    250: "bloodthorn",
    252: "echo_sabre",
    254: "glimmer_cape",
    256: "aeon_disk",
    257: "tome_of_knowledge",
    259: "kaya",
    260: "refresher_shard",
    261: "crown",
    263: "hurricane_pike",
    265: "infused_raindrop",
    267: "spirit_vessel",
    269: "holy_locket",
    271: "ultimate_scepter_2",
    273: "kaya_and_sange",
    277: "yasha_and_kaya",
    279: "ring_of_tarrasque",
    // Neutral Items (Tier 1-5)
    287: "keen_optic",
    288: "grove_bow",
    289: "quickening_charm",
    290: "philosophers_stone",
    291: "force_boots",
    292: "desolator_2",
    294: "seer_stone",
    297: "vampire_fangs",
    298: "craggy_coat",
    300: "timeless_relic",
    301: "mirror_shield",
    302: "elixer",
    304: "recipe_trident",
    306: "ironwood_tree",
    307: "royal_jelly",
    308: "pupils_gift",
    309: "ring_of_aquila",
    310: "imp_claw",
    311: "flicker",
    312: "spy_gadget",
    313: "spider_legs",
    317: "arcane_ring",
    326: "ocean_heart",
    330: "broom_handle",
    331: "trusty_shovel",
    334: "faded_broach",
    335: "paladin_sword",
    336: "orb_of_destruction",
    349: "titan_sliver",
    354: "repair_kit",
    355: "mind_breaker",
    356: "third_eye",
    357: "spell_prism",
    358: "prince_knife",
    359: "ex_machina",
    360: "fallen_sky",
    361: "pirate_hat",
    362: "essence_ring",
    363: "clumsy_net",
    364: "witless_shako",
    365: "vambrace",
    366: "ninja_gear",
    370: "illusionists_cape",
    371: "havoc_hammer",
    372: "panic_button",
    373: "apex",
    374: "ballista",
    375: "woodland_striders",
    376: "trident",
    377: "demonicon",
    379: "book_of_shadows",
    381: "giant_ring",
    473: "voodoo_mask",
    485: "blitz_knuckles",
    533: "witch_blade",
    534: "recipe_witch_blade",
    565: "aghanims_shard",
    569: "orb_of_corrosion",
    571: "falcon_blade",
    573: "mage_slayer",
    574: "recipe_mage_slayer",
    577: "gleipnir",
    578: "recipe_gleipnir",
    585: "eternal_shroud",
    588: "helm_of_the_overlord",
    593: "fluffy_hat",
    596: "falcon_blade",
    600: "revenant_brooch",
    603: "overwhelming_blink",
    604: "swift_blink",
    605: "arcane_blink",
    606: "recipe_overwhelming_blink",
    607: "recipe_swift_blink",
    608: "recipe_arcane_blink",
    609: "gungir",
    610: "recipe_gungir",
    612: "wind_waker",
    635: "boots_of_bearing",
    636: "recipe_boots_of_bearing",
    637: "penta_edged_sword",
    638: "recipe_penta_edge_sword",
    640: "eye_of_the_vizier",
    653: "wraith_pact",
    676: "recipe_wraith_pact",
    677: "revenants_brooch",
    680: "recipe_devastator",
    690: "recipe_blood_grenade",
    692: "blood_grenade",
    // More neutral items
    834: "specialists_array",
    835: "dagger_of_ristul",
    836: "lance_of_pursuit",
    837: "occult_bracelet",
    838: "tome_of_aghanim",
    840: "seeds_of_serenity",
    849: "unwavering_condition",
    908: "phylactery",
    911: "recipe_phylactery",
    931: "disperser",
    932: "recipe_disperser",
    // Aghs upgrades
    1466: "aghanims_blessing",
    1021: "parasma",
    1022: "recipe_parasma",
    1076: "angels_demise",
    // Neutral items with high IDs
    1091: "khanda",
    1097: "recipe_khanda",
    1107: "dandelion_amulet",
    1127: "cactus",
    1128: "light_collector",
    1156: "gloombane",
    1565: "vindicators_axe",
    1603: "safety_bubble",
};

/**
 * Get item image URL from Steam CDN.
 * @param itemId - Dota 2 item ID
 * @returns URL to the item image
 */
export function getItemImageUrl(itemId: number): string | null {
    if (!itemId || itemId === 0) return null;

    const itemName = ITEM_NAMES[itemId];
    if (!itemName) {
        // Try generic fallback
        return null;
    }

    return `https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/items/${itemName}.png`;
}

/**
 * Get item display name (human readable).
 */
export function getItemDisplayName(itemId: number): string {
    const name = ITEM_NAMES[itemId];
    if (!name) return `Item #${itemId}`;

    // Convert snake_case to Title Case
    return name
        .split('_')
        .map(word => word.charAt(0).toUpperCase() + word.slice(1))
        .join(' ');
}

/**
 * Get item image URL from internal item name (e.g., "tango", "boots").
 * Used for purchase_time data which uses internal names.
 */
export function getItemImageUrlByName(itemName: string): string {
    return `https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/items/${itemName}.png`;
}

/**
 * Convert snake_case item name to display name.
 */
export function getDisplayNameFromItemName(itemName: string): string {
    return itemName
        .split('_')
        .map(word => word.charAt(0).toUpperCase() + word.slice(1))
        .join(' ');
}
